//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDinet.ServicioWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWCF.IMovInventarioService")]
    public interface IMovInventarioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovInventarioService/Listar", ReplyAction="http://tempuri.org/IMovInventarioService/ListarResponse")]
        CapaEntidad.MovInventario[] Listar(CapaEntidad.FiltroInventario filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovInventarioService/Listar", ReplyAction="http://tempuri.org/IMovInventarioService/ListarResponse")]
        System.Threading.Tasks.Task<CapaEntidad.MovInventario[]> ListarAsync(CapaEntidad.FiltroInventario filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovInventarioService/Guardar", ReplyAction="http://tempuri.org/IMovInventarioService/GuardarResponse")]
        void Guardar(CapaEntidad.MovInventario mov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovInventarioService/Guardar", ReplyAction="http://tempuri.org/IMovInventarioService/GuardarResponse")]
        System.Threading.Tasks.Task GuardarAsync(CapaEntidad.MovInventario mov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovInventarioService/Editar", ReplyAction="http://tempuri.org/IMovInventarioService/EditarResponse")]
        void Editar(CapaEntidad.MovInventario mov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovInventarioService/Editar", ReplyAction="http://tempuri.org/IMovInventarioService/EditarResponse")]
        System.Threading.Tasks.Task EditarAsync(CapaEntidad.MovInventario mov);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovInventarioService/Eliminar", ReplyAction="http://tempuri.org/IMovInventarioService/EliminarResponse")]
        void Eliminar(string codCia, string comp, string alm, string tipoMov, string tipoDoc, string nroDoc, string codItem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMovInventarioService/Eliminar", ReplyAction="http://tempuri.org/IMovInventarioService/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(string codCia, string comp, string alm, string tipoMov, string tipoDoc, string nroDoc, string codItem);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMovInventarioServiceChannel : WebAppDinet.ServicioWCF.IMovInventarioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MovInventarioServiceClient : System.ServiceModel.ClientBase<WebAppDinet.ServicioWCF.IMovInventarioService>, WebAppDinet.ServicioWCF.IMovInventarioService {
        
        public MovInventarioServiceClient() {
        }
        
        public MovInventarioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MovInventarioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovInventarioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MovInventarioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaEntidad.MovInventario[] Listar(CapaEntidad.FiltroInventario filtro) {
            return base.Channel.Listar(filtro);
        }
        
        public System.Threading.Tasks.Task<CapaEntidad.MovInventario[]> ListarAsync(CapaEntidad.FiltroInventario filtro) {
            return base.Channel.ListarAsync(filtro);
        }
        
        public void Guardar(CapaEntidad.MovInventario mov) {
            base.Channel.Guardar(mov);
        }
        
        public System.Threading.Tasks.Task GuardarAsync(CapaEntidad.MovInventario mov) {
            return base.Channel.GuardarAsync(mov);
        }
        
        public void Editar(CapaEntidad.MovInventario mov) {
            base.Channel.Editar(mov);
        }
        
        public System.Threading.Tasks.Task EditarAsync(CapaEntidad.MovInventario mov) {
            return base.Channel.EditarAsync(mov);
        }
        
        public void Eliminar(string codCia, string comp, string alm, string tipoMov, string tipoDoc, string nroDoc, string codItem) {
            base.Channel.Eliminar(codCia, comp, alm, tipoMov, tipoDoc, nroDoc, codItem);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(string codCia, string comp, string alm, string tipoMov, string tipoDoc, string nroDoc, string codItem) {
            return base.Channel.EliminarAsync(codCia, comp, alm, tipoMov, tipoDoc, nroDoc, codItem);
        }
    }
}
